### ISSUE TITLE
Offset Inventory text in GUI

### ISSUE THREAD

**Issue by Boy0000** [McTsts/shader-utilities#17]
Would it  be possible to implement a shader that could offset this text in specific GUIs?
Looking at using some custom GUIs but only current way to remove it is edit the lang-file, which removes it from normal chests aswell

![image](https://github.com/McTsts/mc-core-shaders/assets/62521371/d9854f47-14db-4b8e-b180-33cba55120e0)

**Comment by McTsts** [comment]
A general solution for this would be very difficult I think as the shaders wont be able to tell it apart either. I would recommend looking into a approach where you have a font element in the custom name of the container that is overlayed on top of the Inventory text, covering it up. It's possible that just putting this element into the name of the Chest is enough to cover up the Inventory text without shader, though if that does not work you should be able to adjust the z Position with the shader to make it work.
