### ISSUE TITLE
[BUG] Remove scoreboard numbers

### ISSUE THREAD

**Issue by Greazi-Times** [McTsts/shader-utilities#6]
So I just tried the number remover from the scoreboard only thing I have now is that somehow it keeps the numbers above a certain amount.
How can I change this?
Like I joined hypixel and sometimes it shows numbers from a certained size.

**Comment by McTsts** [comment]
Yeah, it only removes a single digit. That's intentional, to minimize the amount of things it could possibly affect. You can increase the amount of characters (by 1) it targets by increasing the value gl_VertexID is being compared to by 4. You may also have to alter the gl_Position checks.

**Comment by Greazi-Times** [comment]
> Yeah, it only removes a single digit. That's intentional, to minimize the amount of things it could possibly affect. You can increase the amount of characters (by 1) it targets by increasing the value gl_VertexID is being compared to by 4. You may also have to alter the gl_Position checks.

Just to confirm.
I tried increasing `gl_VertexID` by 1 and it works. I did not need to change or alter the gl_Position at all.
