### ISSUE TITLE
[Question] Lower mc version support

### ISSUE THREAD

**Issue by Greazi-Times** [McTsts/shader-utilities#7]
How can I make the scoreboard numbers work on lower minecraft versions as well?

**Comment by 5uso** [comment]
Core shaders exist only on 1.17 and higher, removing numbers from the sidebar on lower versions requires editing the munber texture and that means you have to replace it everywhere where you want the number to be readable (which isn't possible on quite a few GUIs).

So... not really a thing

**Comment by McTsts** [comment]
In versions before core shaders existed, we used what we call 0fix instead. Here's a video on it: https://www.youtube.com/watch?v=l3L23dlR4jQ

Don't do it.

**Comment by McTsts** [comment]
Actually if you're before 1.15 you can set the opacity of the number to a certain value and the number will disappear and remain visible (enough) in most places. I believe the opacity value was something around ~226 you can try some values and keep decreasing the opacity until it works if you're in pre 1.15

**Comment by Greazi-Times** [comment]
Oke thank you for your honest opinion guys.
I will leave it as it is and unfortunately keep the number on lower versions.
